version: '3.9'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - staticfiles:/camagru/staticfiles
      - media:/camagru/media
      - ssl_data:/etc/nginx/ssl
    env_file:
      - .env
    ports:
      - 8001:8001
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - staticfiles:/camagru/staticfiles
      - media:/camagru/media
      - ssl_data:/etc/nginx/ssl
    ports:
      - 8000:8000
      - 8443:8443
    depends_on:
      - web

volumes:
  staticfiles:
  media:
  ssl_data: